-- O tenant deve ser definido pela sessao ou por uma rotina administrativa explicita.
-- Nenhuma insercao pode assumir silenciosamente a empresa JMIX.
ALTER TABLE "Usuario" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Cliente" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Obra" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Fornecedor" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "CentroCustoCompra" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "CatalogoCompra" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "PlanoConta" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Equipamento" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrdemCompra" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrdemCompraItem" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrdemCompraParcela" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Orcamento" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrcamentoFormacaoPreco" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrcamentoCenario" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrcamentoFrente" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrcamentoItem" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrcamentoPremissa" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrcamentoPropostaComercial" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "OrcamentoPropostaOpcional" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Material" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Servico" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Colaborador" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "PrecoClienteObra" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Ficha" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "FichaRomaneio" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "LancamentoDiario" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "LancamentoRomaneio" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "LeituraEquipamento" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "PlanoManutencao" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "AgendaManutencao" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "AgendaProgramacao" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "ManutencaoExecutada" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "AlertaManutencao" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "AnexoManutencao" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Medicao" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "MedicaoItem" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "HistoricoAlteracao" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "Anexo" ALTER COLUMN "empresaId" DROP DEFAULT;
ALTER TABLE "LogAuditoria" ALTER COLUMN "empresaId" DROP DEFAULT;

-- Codigos e documentos operacionais sao unicos dentro da empresa, nao na plataforma inteira.
DROP INDEX IF EXISTS "Cliente_codigo_key";
DROP INDEX IF EXISTS "Cliente_cpf_key";
DROP INDEX IF EXISTS "Cliente_cnpj_key";
DROP INDEX IF EXISTS "Obra_codigo_key";
DROP INDEX IF EXISTS "Obra_clienteId_codigo_key";
DROP INDEX IF EXISTS "Fornecedor_codigo_key";
DROP INDEX IF EXISTS "Fornecedor_cnpj_key";
DROP INDEX IF EXISTS "CentroCustoCompra_codigo_key";
DROP INDEX IF EXISTS "CatalogoCompra_codigo_key";
DROP INDEX IF EXISTS "PlanoConta_classificacao_key";
DROP INDEX IF EXISTS "Equipamento_placaOuTag_key";
DROP INDEX IF EXISTS "OrdemCompra_numeroOrdem_key";
DROP INDEX IF EXISTS "Orcamento_codigo_key";
DROP INDEX IF EXISTS "Material_codigoMaterial_key";
DROP INDEX IF EXISTS "Servico_codigo_key";
DROP INDEX IF EXISTS "Colaborador_codigo_key";
DROP INDEX IF EXISTS "Medicao_codigoMedicao_key";

CREATE UNIQUE INDEX "Cliente_empresaId_codigo_key" ON "Cliente"("empresaId", "codigo");
CREATE UNIQUE INDEX "Cliente_empresaId_cpf_key" ON "Cliente"("empresaId", "cpf");
CREATE UNIQUE INDEX "Cliente_empresaId_cnpj_key" ON "Cliente"("empresaId", "cnpj");
CREATE UNIQUE INDEX "Obra_empresaId_codigo_key" ON "Obra"("empresaId", "codigo");
CREATE UNIQUE INDEX "Fornecedor_empresaId_codigo_key" ON "Fornecedor"("empresaId", "codigo");
CREATE UNIQUE INDEX "Fornecedor_empresaId_cnpj_key" ON "Fornecedor"("empresaId", "cnpj");
CREATE UNIQUE INDEX "CentroCustoCompra_empresaId_codigo_key" ON "CentroCustoCompra"("empresaId", "codigo");
CREATE UNIQUE INDEX "CatalogoCompra_empresaId_codigo_key" ON "CatalogoCompra"("empresaId", "codigo");
CREATE UNIQUE INDEX "PlanoConta_empresaId_classificacao_key" ON "PlanoConta"("empresaId", "classificacao");
CREATE UNIQUE INDEX "Equipamento_empresaId_placaOuTag_key" ON "Equipamento"("empresaId", "placaOuTag");
CREATE UNIQUE INDEX "OrdemCompra_empresaId_numeroOrdem_key" ON "OrdemCompra"("empresaId", "numeroOrdem");
CREATE UNIQUE INDEX "Orcamento_empresaId_codigo_key" ON "Orcamento"("empresaId", "codigo");
CREATE UNIQUE INDEX "Material_empresaId_codigoMaterial_key" ON "Material"("empresaId", "codigoMaterial");
CREATE UNIQUE INDEX "Servico_empresaId_codigo_key" ON "Servico"("empresaId", "codigo");
CREATE UNIQUE INDEX "Colaborador_empresaId_codigo_key" ON "Colaborador"("empresaId", "codigo");
CREATE UNIQUE INDEX "Medicao_empresaId_codigoMedicao_key" ON "Medicao"("empresaId", "codigoMedicao");
